CodingForEntrepreneurs/urls.py
from django.contrib import admin
from django.urls import path, include
# from patients.views import contactview,aboutview,RegisterView
from questions.views import SignUp
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework import routers
from CodingForEntrepreneurs.api.views import QuestionViewSet, PatientViewSet, ExamViewSet, ResultViewSet, Detailed_ScoreViewSet,PatientloginSet
from . import views

router1 = routers.DefaultRouter()
router1.register(r'questions', QuestionViewSet)

router2 = routers.DefaultRouter()
router2.register(r'patients', PatientViewSet)

router3 = routers.DefaultRouter()
router3.register(r'exams', ExamViewSet)

router4 = routers.DefaultRouter()
router4.register(r'results', ResultViewSet)

router5 = routers.DefaultRouter()
router5.register(r'detailed_score', Detailed_ScoreViewSet)

router6 = routers.DefaultRouter()
router6.register(r'p_login', PatientloginSet, base_name='MyModel')



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
# urlpatterns = [
    
#     #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]

urlpatterns = [
    path(r'admin/', admin.site.urls),
    # path(r'patients/', include('patients.urls', namespace='patients')),
    path(r'question/', include('questions.urls', namespace='question')),
    # path(r'contact/', contactview.as_view(), name='contact'),
    # path(r'about/', aboutview.as_view(), name='about'),
    # # path(r'accounts/login/', auth_views.LoginView.as_view(), name = 'login'),
    # path(r'logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    # path(r'api/p_login', PatientloginSet.as_view(), name = 'p_login'),
    path(r'api/', include(router1.urls)),
    path(r'api/', include(router2.urls)),
    path(r'api/', include(router3.urls)),
    path(r'api/', include(router4.urls)),
    path(r'api/', include(router5.urls)),
    path(r'api/', include(router6.urls)),
    # path(r'api/create/', PatientCreateSet.as_view()),
    path(r'', views.angular_view, name='home'),
    path(r'reg/', views.register_view),
    # path(r'', TemplateView.as_view(template_name='home.html'), name='home'),
    path(r'users/', include('questions.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'signup/',SignUp.as_view(), name='signup'),
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from questions.views import QcreateView,QDetailView,QListView,QUpdateView

from . import views
app_name = 'Question'
urlpatterns = [
    
    path(r'view/',QDetailView.as_view(), name='q_view'),
    #path(r'name/',views.question_view, name='q_name'),
    path(r'create/',QcreateView.as_view(), name='q_create'),
    path(r'update/<pk>/',QUpdateView.as_view(), name='q_update'),
    path(r'plog/',views.p_login, name='plog'),
    path(r'result/',views.result, name='result'),


    

   

   

]

templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

templates/snippets/js.html
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class= 'container'> 
        <h1> Welcome </h1>  
        <a href="{% url 'Patient:patients_name'%}">PATIENT</a>
        <a href="{% url 'Question:q_view'%}">QUESTION</a>
        <a href="{% url 'contact'%}">CONTACT</a>
        <a href="{% url 'about'%}">ABOUT</a>
        <a href="{% url 'logout'%}">LOGOUT</a>
</div>

 