CodingForEntrepreneurs/urls.py
from django.contrib import admin
from django.urls import path, include
# from patients.views import contactview,aboutview,RegisterView
from questions.views import SignUp
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework import routers
from CodingForEntrepreneurs.api.views import QuestionViewSet, PatientViewSet, ExamViewSet, ResultViewSet, Detailed_ScoreViewSet,PatientloginSet
from . import views

router1 = routers.DefaultRouter()
router1.register(r'questions', QuestionViewSet)

router2 = routers.DefaultRouter()
router2.register(r'patients', PatientViewSet)

router3 = routers.DefaultRouter()
router3.register(r'exams', ExamViewSet)

router4 = routers.DefaultRouter()
router4.register(r'results', ResultViewSet)

router5 = routers.DefaultRouter()
router5.register(r'detailed_score', Detailed_ScoreViewSet)

router6 = routers.DefaultRouter()
router6.register(r'p_login', PatientloginSet, base_name='MyModel')



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
# urlpatterns = [
    
#     #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]

urlpatterns = [
    path(r'admin/', admin.site.urls),
    # path(r'patients/', include('patients.urls', namespace='patients')),
    path(r'question/', include('questions.urls', namespace='question')),
    # path(r'contact/', contactview.as_view(), name='contact'),
    # path(r'about/', aboutview.as_view(), name='about'),
    # # path(r'accounts/login/', auth_views.LoginView.as_view(), name = 'login'),
    # path(r'logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    # path(r'api/p_login', PatientloginSet.as_view(), name = 'p_login'),
    path(r'api/', include(router1.urls)),
    path(r'api/', include(router2.urls)),
    path(r'api/', include(router3.urls)),
    path(r'api/', include(router4.urls)),
    path(r'api/', include(router5.urls)),
    path(r'api/', include(router6.urls)),
    # path(r'api/create/', PatientCreateSet.as_view()),
    path(r'', views.angular_view, name='home'),
    path(r'reg/', views.register_view),
    # path(r'', TemplateView.as_view(template_name='home.html'), name='home'),
    path(r'users/', include('questions.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'signup/',SignUp.as_view(), name='signup'),
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from questions.views import QcreateView,QDetailView,QListView,QUpdateView

from . import views
app_name = 'Question'
urlpatterns = [
    
    path(r'view/',QDetailView.as_view(), name='q_view'),
    #path(r'name/',views.question_view, name='q_name'),
    path(r'create/',QcreateView.as_view(), name='q_create'),
    path(r'update/<pk>/',QUpdateView.as_view(), name='q_update'),
    path(r'plog/',views.p_login, name='plog'),
    path(r'result/',views.result, name='result'),


    

   

   

]

questions/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

User = settings.AUTH_USER_MODEL

class Patient(AbstractUser):
    
   
    patient_ID = models.AutoField(primary_key=True)
    # email = models.EmailField(default = '', verbose_name='email address', max_length=255, unique=True, null=True)
    age = models.IntegerField(null=True)
    school = models.CharField(max_length=50, default='')
    grade = models.IntegerField(null=True)
    gender = models.CharField(max_length=50, default='')

    USERNAME_FIELD = 'username'


    def __str__(self):
        return str(self.patient_ID)



class Question(models.Model):
    #owner = models.ForeignKey(User, on_delete=models.CASCADE) #class_instance.model_set.all()
    ques_ID = models.AutoField(primary_key=True)
    audio = models.FileField(null=True, blank=True, upload_to="audios/")
    correct_answer = models.CharField(max_length=50, default='')


class Exam(models.Model):
    exam_ID = models.AutoField(primary_key=True)
    patient_ID = models.ForeignKey(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.exam_ID)
	
	

class Result(models.Model):
    res_ID = models.AutoField(primary_key=True)
    exam_ID = models.ForeignKey(Exam, on_delete=models.CASCADE)
    p_ID = models.ForeignKey(Patient, on_delete=models.CASCADE, default='')
    hits = models.IntegerField()
    misses = models.IntegerField()
    accuracy = models.FloatField()
		
class Detailed_Score(models.Model):
    exam_ID = models.ForeignKey(Exam, on_delete=models.CASCADE)
    ques_ID = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_submitted = models.CharField(max_length=50, default='')
    class Meta:
        unique_together = (('exam_ID', 'ques_ID'),)
	


			
   

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/index.html
  {% extends 'base.html' %}

  {% block title %}Home{% endblock %}
  {% block content %}
  {% if user.is_authenticated %}
    Hi {{ user.name }}!
    {{ request.user.patient_ID }}
    <!DOCTYPE html>

    {% load static %}  
    
      <html ng-app="quizApp">
      <head>
        <meta charset="utf-8" />
        <title>QuizApp</title>
        <link rel="stylesheet" href="{% static "style.css" %}"/>
        <script src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
        <script src="https://code.angularjs.org/1.3.0-rc.1/angular.min.js"></script>
        <script src="https://code.angularjs.org/1.3.0-rc.1/angular-route.min.js"></script>
          <script>
            // var template = "{% static 'template.html' %}";
        </script>
        <script src="{% static "app.js" %}"/></script>
      </head>
      
      <body>
          {% verbatim %}    
        <div class="container">
          <h1 class="title">QuizApp</h1>
          <div ng-view></div>
        </div>
        {% endverbatim %}
      </body>
      </html>
      
    <p><a href="{% url 'logout' %}">LOGOUT</a></p>
  {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">LOGIN</a> 
    <a href="{% url 'signup' %}">SIGNUP</a>

    {% endif %}
  {% endblock %}

templates/plog.html
    
        {% if user.is_authenticated %}
            Hi {{ user.name }}!
            {{ request.user.patient_ID }}
        {% endif %}

templates/result.html
<h1> Question List</h1>



<ul>
{% for obj in result_list %}


<strong> {{obj.p_ID}} </strong>
{{obj.exam_ID}}
{{obj.hits}}
{{obj.misses}}
{{obj.accuracy}}
<br>

{% endfor %}
</ul>

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}